install:
	bash setup.sh install

lint:
	bash setup.sh lint

lint-ci:
	bash setup.sh lint:ci

test-ci:
	bash setup.sh test:ci

test:
	bash setup.sh run-tests

test-wheel-locally:
	bash setup.sh test:wheel-locally

build:
	bash setup.sh build

clean:
	bash setup.sh clean
